### ISSUE TITLE
loading indicator for long loading wallet

### ISSUE THREAD

**Issue by Zergity** [ezDeFi/web3-react-modal#10]
e.g. Torus

**Comment by CaoThien96** [comment]
Is it necessary to support loading in the library.
Client can control loading show and hide simply by
`
const { account, active, activate, deactivate } = useWeb3React()
const [ loading, setLoading ] = useState(false)

onConnect(()=>{
  .......
  setLoading(true)
})

return (
   ...
  {!active && loading  && renderLoadingComp()}
)

`

**Comment by Zergity** [comment]
> Is it necessary to support loading in the library. Client can control loading show and hide simply by
> 
> ```
> const { account, active, activate, deactivate } = useWeb3React()
> const [ loading, setLoading ] = useState(false)
> 
> onConnect(()=>{
>   .......
>   setLoading(true)
> })
> 
> return (
>    ...
>   {!active && loading  && renderLoadingComp()}
> )
> ```
> 
> @Zergity

makes sense, let backlog this for now
